import React from 'react'
import "../globals.css";
import ServerNavbar from './components/ServerNavbar';
import { Metadata } from 'next';
import { Providers } from '../providers';
export const metadata: Metadata = {
  title: "TrendiZip Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
        <html lang="en">
              <head>
        <link rel="icon" href="/navlogo.png" />
      </head>
        <body
          className={`w-full h-full antialiased`}
        >
          <Providers>
            <ServerNavbar/>
            {children}
          </Providers>
        </body>
      </html>
  )
}