import React from 'react'
import "../globals.css";
import ServerNavbar from './components/ServerNavbar';
import { Metadata } from 'next';
export const metadata: Metadata = {
  title: "TrendiZip Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
        <html lang="en">
        <body
          className={`w-full h-full antialiased`}
        >
          <ServerNavbar/>
          {children}
        </body>
      </html>
  )
}